phrase:
  access_token: fd09efa5416bcc5a721caf1636c12ebf84b734967e2bcc01a095a00641247c99
  project_id: a43fd95b6f69e95aaeb482b5911749cf
  push:
    sources:
    - file: ./en.json
      params:
        locale_id: en-US
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
